//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public int ContactDetailId { get; set; }
        public string MobilePhone { get; set; }
        public string HomeNumber { get; set; }
        public string OfficeNumber { get; set; }
        public string TwitterAlias { get; set; }
        public string FaceBook { get; set; }
        public string LinkedIn { get; set; }
        public string SkypeId { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
