//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.LineItems = new HashSet<LineItem>();
            this.Categories = new HashSet<Category>();
        }
    
        public int ProductId { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int LineItemId { get; set; }
    
        public virtual ICollection<LineItem> LineItems { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
